---
roles:

- name : andrewrothstein.anaconda

- name : gantsign.visual-studio-code

- name : mhalano.skypeforlinux    

- name : ngetchell.ms_teams
- name : andrewrothstein.alpine-glibc-shim
- name : andrewrothstein.bash
- name : andrewrothstein.unarchive-deps
