---

    - name: Run a shell command and register its output as a variable
      command: "uname -r "
      register: os_version
      ignore_errors: true

    - name: install default SO headers
      shell: |
        """apt-get install linux-headers-{{os_version['stdout_lines'][0]}}"""
      ignore_errors: yes

    - name: Install basic packages
      apt: name={{ item }}
          state=latest
      with_items: "{{ packages}}"
      tags: [ packages ]

    - name: Reinstall libc6
      shell: |
        apt-get install --reinstall libc6-i386
      tags: [ packages ]


